import path from 'node:path';

const BY_EXTENSION: Record<string, string> = {
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.py': 'python',
  '.go': 'go',
  '.rs': 'rust',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.scala': 'scala',
  '.sc': 'scala',
  '.cs': 'csharp',
  '.rb': 'ruby',
  '.rake': 'ruby',
  '.ru': 'ruby',
  '.gemspec': 'ruby',
  '.php': 'php',
  '.swift': 'swift',
  '.m': 'objective-c',
  '.c': 'c',
  '.h': 'c',
  '.cc': 'cpp',
  '.cpp': 'cpp',
  '.cxx': 'cpp',
  '.c++': 'cpp',
  '.hpp': 'cpp',
  '.hh': 'cpp',
  '.hxx': 'cpp',
  '.ipp': 'cpp',
  '.inl': 'cpp',
  '.tpp': 'cpp',
  '.cppm': 'cpp',
  '.ixx': 'cpp',
  '.cu': 'cpp',
  '.cuh': 'cpp',
  '.sql': 'sql',
  '.sh': 'shell',
  '.bash': 'shell',
  '.zsh': 'shell',
  '.ksh': 'shell',
  '.bats': 'shell',
  '.ps1': 'shell',
  '.psm1': 'shell',
  '.tf': 'terraform',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.json': 'json',
  '.toml': 'toml',
  '.md': 'markdown',
  '.html': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.proto': 'protobuf',
  '.dart': 'dart',
  '.ex': 'elixir',
  '.exs': 'elixir',
};

const BY_NAME: Record<string, string> = {
  Rakefile: 'ruby',
  Gemfile: 'ruby',
  Dockerfile: 'dockerfile',
  Makefile: 'makefile',
  Jenkinsfile: 'groovy',
};

export function detectLanguage(filePath: string): string {
  const base = path.basename(filePath);
  if (BY_NAME[base]) return BY_NAME[base];
  if (base.startsWith('Dockerfile')) return 'dockerfile';
  return BY_EXTENSION[path.extname(base).toLowerCase()] ?? 'text';
}
