import { JS, type PatternRule } from './types';

const SANITIZED = /DOMPurify|sanitiz|purify|escapeHtml|xss\(/i;

/** JavaScript / TypeScript / Vue / Svelte rules. */
export const JS_RULES: PatternRule[] = [
  {
    id: 'js-eval',
    languages: JS,
    regex: /(?<![\w$.])eval\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-95',
    skill: 'javascript/security/code-execution',
    message: '`eval()` runs a string as code: any attacker-influenced part becomes code injection.',
    help: 'Parse data with JSON.parse or dispatch through a lookup table instead of evaluating strings.',
  },
  {
    id: 'js-new-function',
    languages: JS,
    regex: /\bnew\s+Function\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-95',
    skill: 'javascript/security/code-execution',
    message:
      '`new Function(...)` compiles a string into code: code injection if any argument is attacker-influenced.',
    help: 'Avoid generating code at runtime; use data-driven logic.',
  },
  {
    id: 'js-string-timer',
    languages: JS,
    regex: /\bset(?:Timeout|Interval|Immediate)\s*\(\s*['"`]/,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-95',
    skill: 'javascript/security/code-execution',
    message: 'A string passed to setTimeout/setInterval is evaluated like eval().',
    help: 'Pass a function instead of a string.',
  },
  {
    id: 'js-inner-html',
    languages: JS,
    regex: /\.(?:inner|outer)HTML\s*\+?=(?!=)/,
    notIf:
      /\.(?:inner|outer)HTML\s*\+?=\s*(?:(?:'[^'$]*'|"[^"$]*"|`[^`$]*`)\s*;?\s*$|DOMPurify|sanitiz|escape)/i,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-79',
    skill: 'web/browser-security/dom-xss',
    message: 'Assigning to innerHTML/outerHTML renders markup: attacker-controlled parts become XSS.',
    help: 'Use textContent / DOM APIs, or sanitize with DOMPurify.',
  },
  {
    id: 'js-html-sink',
    languages: JS,
    regex: /\b(?:document\.write(?:ln)?|\.insertAdjacentHTML|\.createContextualFragment)\s*\(/,
    notIf: SANITIZED,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-79',
    skill: 'web/browser-security/dom-xss',
    message: 'HTML sink (document.write / insertAdjacentHTML): attacker-controlled parts become XSS.',
    help: 'Build DOM nodes or sanitize the markup first.',
  },
  {
    id: 'js-dangerously-set-inner-html',
    languages: JS,
    regex: /dangerouslySetInnerHTML\s*=\s*\{/,
    notIf: SANITIZED,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-79',
    skill: 'javascript/react/xss',
    message: '`dangerouslySetInnerHTML` bypasses React escaping: unsanitized user content is XSS.',
    help: 'Render text normally, or sanitize with DOMPurify right at the call site.',
  },
  {
    id: 'js-v-html',
    languages: ['vue', 'html'],
    regex: /\sv-html\s*=/,
    notIf: SANITIZED,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-79',
    skill: 'javascript/vue/xss',
    message: '`v-html` renders raw HTML: unsanitized user content is XSS.',
    help: 'Use text interpolation, or sanitize the HTML before binding it.',
  },
  {
    id: 'js-svelte-html',
    languages: ['svelte'],
    regex: /\{@html\s/,
    notIf: SANITIZED,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-79',
    skill: 'javascript/svelte/xss',
    message: '`{@html …}` renders raw HTML: unsanitized user content is XSS.',
    help: 'Render text, or sanitize before using {@html}.',
  },
  {
    id: 'js-exec-interpolation',
    languages: JS,
    regex:
      /\b(?:exec|execSync)\s*\(\s*(?:`[^`]{0,300}\$\{|(?:'[^']{0,300}'|"[^"]{0,300}")\s*\+|[A-Za-z_$][\w$.]{0,60}\s*\+)/,
    notIf: /(?:re|regex|regexp|pattern|rx|matcher)\w*\.exec\s*\(|\/[^/\n]{1,200}\/[dgimsuy]{0,6}\.exec\s*\(/i,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-78',
    skill: 'javascript/security/shell-commands',
    message:
      'Shell command built from interpolated/concatenated values: command injection if any part is attacker-controlled.',
    help: 'Use execFile/spawn with an argument array (no shell) and validate values against an allowlist.',
  },
  {
    id: 'js-spawn-shell',
    languages: JS,
    regex: /\b(?:spawn|spawnSync|execFile|execFileSync)\s*\([^;]{0,300}\bshell\s*:\s*true\b/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-78',
    skill: 'javascript/security/shell-commands',
    message:
      '`shell: true` makes spawn/execFile parse the arguments with a shell: metacharacters inject commands.',
    help: 'Drop `shell: true` and pass arguments as an array.',
  },
  {
    id: 'js-sql-template',
    languages: JS,
    regex:
      /(?<![\w$.])`\s*(?:SELECT\b[^`]{0,200}\bFROM|INSERT\s+INTO|UPDATE\s+[\w."]{1,80}\s+SET|DELETE\s+FROM|REPLACE\s+INTO|MERGE\s+INTO)\b[^`]{0,400}\$\{/i,
    window: 3,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-89',
    skill: 'security/core',
    message:
      'SQL built with template-literal interpolation: SQL injection if any interpolated value is user-controlled.',
    help: 'Use placeholders ($1, ?) or a tagged-template API that parameterizes values (sql`…`).',
  },
  {
    id: 'js-tls-reject-unauthorized',
    languages: [...JS, 'yaml', 'json', 'shell', 'dockerfile'],
    regex: /\brejectUnauthorized\s*:\s*false\b|NODE_TLS_REJECT_UNAUTHORIZED["']?\s*[:=]\s*["']?0\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-295',
    skill: 'security/crypto',
    message: 'TLS certificate verification disabled: connections can be intercepted (MITM).',
    help: 'Keep verification on; trust a private CA via the `ca` option or NODE_EXTRA_CA_CERTS.',
  },
  {
    id: 'js-jwt-decode',
    languages: JS,
    regex: /\bjwt\.decode\s*\(|\bjwtDecode\s*\(|\bjwt_decode\s*\(/,
    severity: 'minor',
    category: 'security',
    confidence: 0.35,
    cwe: 'CWE-347',
    skill: 'security/auth',
    message:
      '`jwt.decode()` does not verify the signature: trusting its claims for authorization accepts forged tokens.',
    help: 'Use jwt.verify() with an explicit `algorithms` list for anything security-relevant.',
  },
  {
    id: 'js-open-redirect',
    languages: JS,
    regex:
      /\bres\.redirect\s*\(\s*(?:\d{3}\s*,\s*)?req(?:uest)?\.(?:query|params|body)\b|\b(?:window\.)?location(?:\.href)?\s*=\s*[^;=]{0,120}(?:location\.(?:search|hash)|searchParams\.get|req\.query)/,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-601',
    skill: 'security/core',
    message: 'Redirect target taken from request data: open redirect (phishing, OAuth token theft).',
    help: 'Redirect only to relative paths or an allowlist of hosts.',
  },
  {
    id: 'js-path-from-request',
    languages: JS,
    regex:
      /\b(?:readFile|readFileSync|createReadStream|createWriteStream|writeFile|writeFileSync|appendFile|unlink|unlinkSync|rmSync|sendFile|download|join|resolve)\s*\([^;]{0,160}\breq(?:uest)?\.(?:query|params|body)\b/,
    notIf: /\bbasename\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-22',
    skill: 'javascript/security/path-traversal',
    message: 'File path built from request data: `../` sequences can read or overwrite arbitrary files.',
    help: 'Resolve against a base directory and reject results outside it.',
  },
  {
    id: 'js-ssrf',
    languages: JS,
    regex:
      /\b(?:fetch|axios(?:\.(?:get|post|put|patch|delete|request))?|got(?:\.\w+)?|needle|superagent\.\w+|https?\.(?:get|request))\s*\(\s*(?:`[^`]{0,80}\$\{\s*)?req(?:uest)?\.(?:query|params|body)\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-918',
    skill: 'security/core',
    message:
      'Outbound request URL taken from request data: SSRF against internal services and cloud metadata.',
    help: 'Allowlist hosts/schemes and block private address ranges after DNS resolution.',
  },
  {
    id: 'js-regexp-from-input',
    languages: JS,
    regex: /\bnew\s+RegExp\s*\(\s*req(?:uest)?\.(?:query|params|body)\b/,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-1333',
    skill: 'javascript/security/regex-dos',
    message: 'Regular expression compiled from request data: ReDoS and regex injection.',
    help: 'Escape the input or use plain string matching.',
  },
  {
    id: 'js-nosql-where',
    languages: JS,
    regex: /['"]?\$where['"]?\s*:/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-943',
    skill: 'databases/mongodb/core',
    message:
      'MongoDB `$where` executes JavaScript on the server: with user input this is NoSQL/code injection.',
    help: 'Use regular query operators.',
  },
  {
    id: 'js-postmessage-wildcard',
    languages: JS,
    regex: /\.postMessage\s*\([^;]{0,200},\s*['"]\*['"]\s*\)/,
    severity: 'minor',
    category: 'security',
    confidence: 0.35,
    cwe: 'CWE-345',
    skill: 'web/browser-security/postmessage',
    message:
      '`postMessage(…, "*")` delivers the data to whatever origin currently controls the target window.',
    help: 'Pass the exact target origin.',
  },
  {
    id: 'js-vm-sandbox',
    languages: JS,
    regex:
      /\bvm\.(?:runInNewContext|runInThisContext|runInContext|compileFunction)\s*\(|\bnew\s+vm\.Script\s*\(/,
    severity: 'minor',
    category: 'security',
    confidence: 0.35,
    cwe: 'CWE-94',
    skill: 'javascript/security/code-execution',
    message: 'Node `vm` is not a security sandbox: untrusted code can escape to the host process.',
    help: 'Run untrusted code in a separate process/isolate with no privileges.',
  },
  {
    id: 'js-foreach-async',
    languages: JS,
    regex: /\.forEach\s*\(\s*async\b/,
    severity: 'major',
    category: 'bug',
    confidence: 0.6,
    skill: 'javascript/core/async-promises',
    message:
      '`forEach` ignores the promises of an async callback: work is not awaited, errors become unhandled rejections and ordering is lost.',
    help: 'Use `for…of` with await, or `await Promise.all(items.map(async …))`.',
  },
  {
    id: 'js-useeffect-async',
    languages: JS,
    regex: /\buseEffect\s*\(\s*async\b/,
    severity: 'major',
    category: 'bug',
    confidence: 0.6,
    skill: 'javascript/react/effects',
    message: '`useEffect(async …)` returns a promise, so React never receives a cleanup function.',
    help: 'Define an async function inside the effect, call it, and return a real cleanup.',
  },
  {
    id: 'js-nan-comparison',
    languages: JS,
    regex: /[!=]==?\s*NaN\b|\bNaN\s*[!=]==?/,
    severity: 'major',
    category: 'bug',
    confidence: 0.7,
    skill: 'javascript/core/numbers',
    message: 'Comparison with NaN is always false (always true for !==): the check never works.',
    help: 'Use Number.isNaN(x).',
  },
  {
    id: 'js-promise-catch-swallow',
    languages: JS,
    regex: /\.catch\s*\(\s*(?:\(\s*\w*\s*\)|\w+)\s*=>\s*(?:\{\s*\}|null|undefined|void 0|false)\s*\)/,
    severity: 'minor',
    category: 'error-handling',
    confidence: 0.35,
    skill: 'javascript/core/async-promises',
    message:
      'Promise rejection swallowed silently: failures disappear and callers continue with missing data.',
    help: 'Log or propagate the error; if ignoring is intended, narrow it to the expected error.',
  },
  {
    id: 'js-insecure-cookie',
    languages: JS,
    regex: /\b(?:httpOnly|secure)\s*:\s*false\b/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-614',
    skill: 'web/browser-security/cookies-storage',
    message:
      'Cookie without HttpOnly/Secure: readable by scripts (token theft via XSS) or sent over plain HTTP.',
    help: 'Set httpOnly: true and secure: true for session/auth cookies.',
  },
];
