import { JVM, type PatternRule } from './types';

const PHP = ['php'] as const;
const CS = ['csharp'] as const;
const GO = ['go'] as const;
const RB = ['ruby'] as const;
const RS = ['rust'] as const;

/** PHP rules. */
const PHP_RULES: PatternRule[] = [
  {
    id: 'php-eval',
    languages: PHP,
    regex: /(?<![\w>$:])(?:eval|assert|create_function)\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-95',
    skill: 'php/security/command-exec',
    message: '`eval` / `assert(string)` / `create_function` execute PHP code from a string.',
    help: 'Remove dynamic code evaluation; use a dispatch table.',
  },
  {
    id: 'php-unserialize',
    languages: PHP,
    regex: /(?<![\w>$:])unserialize\s*\(/,
    notIf: /allowed_classes['"]?\s*=>\s*false/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-502',
    skill: 'php/security/deserialization',
    message: '`unserialize()` on untrusted data allows PHP object injection (gadget chains, RCE).',
    help: "Use json_decode, or pass ['allowed_classes' => false].",
  },
  {
    id: 'php-request-to-sink',
    languages: PHP,
    regex:
      /\b(?:shell_exec|system|passthru|exec|popen|proc_open|eval|include|require|include_once|require_once|file_get_contents|fopen|readfile|unlink)\s*\(?[^;]{0,120}\$_(?:GET|POST|REQUEST|COOKIE|FILES)\b/,
    notIf: /escapeshellarg|escapeshellcmd|basename\s*\(|intval\s*\(|\(int\)/,
    severity: 'critical',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-78',
    skill: 'php/security/request-trust',
    message: 'Request data flows straight into a command/file/include sink: injection or path traversal.',
    help: 'Validate against an allowlist and escape with escapeshellarg / basename.',
  },
  {
    id: 'php-shell-variable',
    languages: PHP,
    regex:
      /\b(?:shell_exec|system|passthru|exec|popen|proc_open)\s*\(\s*(?:"[^"]{0,200}\$\w|[^;]{0,120}\.\s*\$\w)/,
    notIf: /escapeshellarg|escapeshellcmd/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-78',
    skill: 'php/security/command-exec',
    message: 'Shell command built from a variable without escapeshellarg: command injection.',
    help: 'Escape every argument with escapeshellarg or avoid the shell.',
  },
  {
    id: 'php-include-variable',
    languages: PHP,
    regex: /\b(?:include|require)(?:_once)?\s*\(?\s*\$/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-98',
    skill: 'php/security/file-access',
    message:
      'include/require with a variable path: local/remote file inclusion if the value is user-influenced.',
    help: 'Map inputs to a fixed list of files.',
  },
  {
    id: 'php-echo-request',
    languages: PHP,
    regex: /\b(?:echo|print)\b[^;]{0,160}\$_(?:GET|POST|REQUEST|COOKIE|SERVER)\b/,
    notIf: /htmlspecialchars|htmlentities|intval|esc_html|esc_attr|\(int\)|json_encode/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-79',
    skill: 'php/security/output-escaping',
    message: 'Request data echoed without escaping: reflected XSS.',
    help: 'Escape with htmlspecialchars($v, ENT_QUOTES).',
  },
  {
    id: 'php-loose-hash-compare',
    languages: PHP,
    regex:
      /(?<![=!])(?:==|!=)\s*(?:md5|sha1|hash|crypt|hash_hmac)\s*\(|\b(?:md5|sha1|hash|crypt|hash_hmac)\s*\([^()]{0,160}\)\s*(?:==|!=)(?!=)/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-697',
    skill: 'php/core/comparisons',
    message: 'Loose comparison of hashes: "0e…" magic hashes compare equal, bypassing the check.',
    help: 'Use hash_equals() for secrets and === otherwise.',
  },
  {
    id: 'php-extract-request',
    languages: PHP,
    regex: /\b(?:extract|parse_str)\s*\(\s*\$_(?:GET|POST|REQUEST|COOKIE)\b|\bparse_str\s*\([^,)]{1,120}\)/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-621',
    skill: 'php/security/request-trust',
    message: '`extract` / single-argument `parse_str` on request data overwrites arbitrary variables.',
    help: 'Read the needed keys explicitly; pass a result array to parse_str.',
  },
];

/** Java / Kotlin / Scala / Groovy rules. */
const JVM_RULES: PatternRule[] = [
  {
    id: 'java-deserialization',
    languages: JVM,
    regex:
      /\bnew\s+(?:ObjectInputStream|XMLDecoder)\s*\(|\benableDefaultTyping\s*\(|\bactivateDefaultTyping\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-502',
    skill: 'java/security/deserialization',
    message:
      'Deserialization of untrusted data (ObjectInputStream / XMLDecoder / Jackson default typing) enables gadget-chain RCE.',
    help: 'Use a data format without polymorphic typing, or an ObjectInputFilter allowlist.',
  },
  {
    id: 'java-jndi-lookup',
    languages: JVM,
    regex: /\.lookup\s*\(\s*(?!["'])[^)]{1,120}\)/,
    fileIf: /javax\.naming|InitialContext|InitialDirContext/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-74',
    skill: 'java/security/expression-injection',
    message:
      'JNDI lookup with a non-constant name: attacker-controlled names load remote objects (Log4Shell-style RCE).',
    help: 'Only look up constant names; never pass user input to JNDI.',
  },
  {
    id: 'java-command-injection',
    languages: JVM,
    regex:
      /\bRuntime\.getRuntime\(\)\.exec\s*\([^;]{0,200}\+|\bnew\s+ProcessBuilder\s*\([^;]{0,200}\+|"(?:sh|bash|\/bin\/sh|\/bin\/bash|cmd(?:\.exe)?)"\s*,\s*"(?:-c|\/c)"\s*,\s*(?!")/i,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'security/core',
    message: 'OS command built by concatenation or run through a shell: command injection.',
    help: 'Pass a fixed program and separate arguments to ProcessBuilder; validate values.',
  },
  {
    id: 'java-weak-cipher',
    languages: JVM,
    regex: /Cipher\.getInstance\s*\(\s*"(?:(?:DES|DESede|RC4|RC2|Blowfish|AES)"|[^"]{0,40}\/ECB\/)/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-327',
    skill: 'java/security/jca-crypto',
    message: 'Weak cipher or ECB mode (plain "AES" defaults to ECB): plaintext patterns leak.',
    help: 'Use AES/GCM/NoPadding with a random 12-byte IV.',
  },
  {
    id: 'java-trust-all',
    languages: JVM,
    regex:
      /\bcheckServerTrusted\s*\([^)]{0,200}\)\s*(?:throws\s+[\w.]+\s*)?\{\s*\}|\bsetHostnameVerifier\s*\([^;]{0,120}(?:ALLOW_ALL|->\s*true|NoopHostnameVerifier)|ALLOW_ALL_HOSTNAME_VERIFIER|NoopHostnameVerifier\.INSTANCE|\bhostnameVerifier\s*\{\s*_\s*,\s*_\s*->\s*true\s*\}/,
    window: 1,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-295',
    skill: 'java/security/tls-trust',
    message: 'TLS trust manager / hostname verifier accepts everything: MITM possible.',
    help: 'Use the default trust manager; add private CAs to a trust store instead.',
  },
  {
    id: 'java-xxe',
    languages: JVM,
    regex:
      /\b(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory|SchemaFactory)\.new(?:Instance|Factory)\s*\(|\bnew\s+(?:SAXReader|SAXBuilder)\s*\(/,
    fileNotIf:
      /disallow-doctype-decl|ACCESS_EXTERNAL_(?:DTD|SCHEMA|STYLESHEET)|FEATURE_SECURE_PROCESSING|IS_SUPPORTING_EXTERNAL_ENTITIES|SUPPORT_DTD|external-general-entities|setExpandEntityReferences\s*\(\s*false/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-611',
    skill: 'java/security/xml-parsers',
    message: 'XML parser created without disabling DTDs / external entities: XXE (file read, SSRF).',
    help: 'Set disallow-doctype-decl (or FEATURE_SECURE_PROCESSING and empty ACCESS_EXTERNAL_* properties).',
  },
  {
    id: 'java-string-reference-equality',
    languages: ['java'],
    regex: /(?<![=!<>])[=!]=\s*"[^"\n]{0,200}"|"[^"\n]{0,200}"\s*[=!]=(?!=)/,
    severity: 'major',
    category: 'bug',
    confidence: 0.55,
    skill: 'java/core/equals-hashcode',
    message: 'Strings compared with == / != compare references: equal strings can compare unequal.',
    help: 'Use .equals() / Objects.equals().',
  },
  {
    id: 'spring-csrf-disabled',
    languages: JVM,
    regex:
      /\.csrf\s*\(\s*\)\s*\.\s*disable\s*\(|\.csrf\s*\([^;]{0,80}\bdisable\b|\bcsrf\s*\{\s*disable\s*\(\s*\)/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-352',
    skill: 'java/spring/security/cors-csrf',
    message:
      'CSRF protection disabled: fine for stateless token APIs, a vulnerability with cookie/session auth.',
    help: 'Keep CSRF enabled when browsers authenticate with cookies.',
  },
];

/** C# rules. */
const CSHARP_RULES: PatternRule[] = [
  {
    id: 'cs-insecure-deserializer',
    languages: CS,
    regex:
      /\b(?:BinaryFormatter|NetDataContractSerializer|SoapFormatter|LosFormatter|ObjectStateFormatter)\b|TypeNameHandling\s*=\s*TypeNameHandling\.(?:All|Auto|Objects|Arrays)\b|\bnew\s+JavaScriptSerializer\s*\(\s*new\s+SimpleTypeResolver/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-502',
    skill: 'csharp/security/deserialization',
    message:
      'Insecure deserializer (BinaryFormatter / TypeNameHandling): untrusted payloads execute gadget chains.',
    help: 'Use System.Text.Json without polymorphic type names.',
  },
  {
    id: 'cs-cert-validation-bypass',
    languages: CS,
    regex:
      /ServerCertificate(?:Custom)?ValidationCallback\s*=\s*[^;]{0,160}(?:=>\s*true\b|DangerousAcceptAnyServerCertificateValidator|return\s+true)/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-295',
    skill: 'csharp/security/tls',
    message: 'Certificate validation callback accepts every certificate: MITM possible.',
    help: 'Remove the callback, or pin the expected certificate/CA.',
  },
  {
    id: 'cs-process-start-concat',
    languages: CS,
    regex: /\bProcess\.Start\s*\([^;]{0,200}(?:\+|\$")/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-78',
    skill: 'csharp/security/process-start',
    message: 'Process started with a concatenated/interpolated command line: argument/command injection.',
    help: 'Use ProcessStartInfo.ArgumentList with separate, validated arguments.',
  },
  {
    id: 'cs-async-void',
    languages: CS,
    regex: /\basync\s+void\s+\w+\s*\(/,
    notIf: /EventArgs\b|\bobject\s+\w*sender\b/,
    severity: 'major',
    category: 'bug',
    confidence: 0.5,
    skill: 'csharp/async/async-void',
    message: '`async void` method: its exceptions crash the process and callers cannot await completion.',
    help: 'Return Task (async void is only for event handlers).',
  },
  {
    id: 'cs-sync-over-async',
    languages: CS,
    regex:
      /\b\w{0,80}Async\s*\([^;]{0,160}\)\s*\.(?:Result\b|Wait\s*\(\s*\)|GetAwaiter\s*\(\s*\)\s*\.GetResult\s*\(\s*\))/,
    severity: 'minor',
    category: 'concurrency',
    confidence: 0.45,
    skill: 'csharp/async/blocking',
    message:
      'Blocking on an async call (.Result / .Wait() / GetResult()) can deadlock under a synchronization context and starves the thread pool.',
    help: 'Make the caller async and await the task.',
  },
];

/** Go rules. */
const GO_RULES: PatternRule[] = [
  {
    id: 'go-insecure-skip-verify',
    languages: GO,
    regex: /\bInsecureSkipVerify\s*:\s*true\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-295',
    skill: 'go/security/tls',
    message: '`InsecureSkipVerify: true` disables TLS certificate checks: MITM possible.',
    help: 'Configure RootCAs for private CAs instead.',
  },
  {
    id: 'go-exec-shell',
    languages: GO,
    regex:
      /\bexec\.Command(?:Context)?\s*\(\s*(?:\w+\s*,\s*)?"(?:sh|bash|\/bin\/sh|\/bin\/bash|cmd(?:\.exe)?)"\s*,\s*"(?:-c|\/c|\/C)"\s*,\s*(?!"[^"]*"\s*\))/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'go/security/os-exec',
    message: 'Command run through `sh -c` with a non-constant script: command injection.',
    help: 'Call the program directly with separate arguments.',
  },
  {
    id: 'go-empty-error-branch',
    languages: GO,
    regex: /\bif\s+err\s*!=\s*nil\s*\{\s*\}/,
    window: 1,
    severity: 'minor',
    category: 'error-handling',
    confidence: 0.5,
    skill: 'go/errors/handling',
    message: 'Error checked but ignored (empty branch): execution continues with invalid results.',
    help: 'Return or handle the error.',
  },
  {
    id: 'go-ignored-error',
    languages: GO,
    regex:
      /,\s*_\s*:?=\s*(?:strconv\.(?:Atoi|Parse\w+)|json\.Marshal\w*|io\.ReadAll|os\.(?:ReadFile|Open|OpenFile|Create)|url\.Parse|time\.Parse(?:Duration)?|\w+\.(?:Query|QueryRow|Exec|Do|Get|Post))\s*\(/,
    severity: 'minor',
    category: 'error-handling',
    confidence: 0.35,
    skill: 'go/errors/handling',
    message:
      'Error of a fallible call discarded with `_`: failures yield zero values that are used as real data.',
    help: 'Check the error.',
  },
  {
    id: 'go-http-no-timeout',
    languages: GO,
    regex:
      /\bhttp\.(?:Get|Post|Head|PostForm)\s*\(|\bhttp\.ListenAndServe(?:TLS)?\s*\(|&?http\.Client\s*\{\s*\}/,
    severity: 'minor',
    category: 'performance',
    confidence: 0.3,
    skill: 'go/http/client',
    message: 'Default net/http client/server has no timeouts: slow peers hang goroutines (Slowloris).',
    help: 'Use an http.Client with Timeout and an http.Server with Read/Write timeouts.',
  },
  {
    id: 'go-sql-sprintf',
    languages: GO,
    regex:
      /fmt\.Sprintf\s*\(\s*["`]\s*(?:SELECT\b[^"`]{0,200}\bFROM|INSERT\s+INTO|UPDATE\s+[\w."]{1,80}\s+SET|DELETE\s+FROM)\b[^"`]{0,300}%[sv]/i,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-89',
    skill: 'go/database/sql/queries-and-rows',
    message: 'SQL built with fmt.Sprintf: values are not parameterized (SQL injection).',
    help: 'Use placeholders ($1 / ?) with db.Query(query, args...).',
  },
];

/** Ruby rules. */
const RUBY_RULES: PatternRule[] = [
  {
    id: 'rb-eval',
    languages: RB,
    regex: /(?<![\w.:])(?:eval|instance_eval|class_eval|module_eval)\b\s*[(\s]\s*(?!do\b|\{)/,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-95',
    skill: 'ruby/security',
    message: '`eval` of a string runs Ruby code: code injection if any part is attacker-influenced.',
    help: 'Use blocks / define_method / a dispatch table.',
  },
  {
    id: 'rb-dynamic-dispatch',
    languages: RB,
    regex:
      /\.(?:send|public_send|__send__|constantize|safe_constantize)\s*\(?\s*params\[|params\[[^\]]{1,60}\]\s*\.(?:constantize|safe_constantize)\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-470',
    skill: 'ruby/security',
    message:
      'Method/class chosen from request params: attackers can call arbitrary methods or instantiate classes.',
    help: 'Map params to an explicit allowlist.',
  },
  {
    id: 'rb-command-interpolation',
    languages: RB,
    regex:
      /\b(?:system|exec|spawn|IO\.popen|Open3\.\w+)\s*\(?\s*"[^"]{0,200}#\{|`[^`]{0,200}#\{|%x[({[][^)}\]]{0,200}#\{/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'ruby/security',
    message: 'Shell command with string interpolation: command injection.',
    help: 'Pass separate arguments: system("cmd", arg1, arg2).',
  },
  {
    id: 'rb-unsafe-deserialization',
    languages: RB,
    regex:
      /\bMarshal\.(?:load|restore)\s*\(|\bYAML\.unsafe_load\s*\(|\bOj\.load\s*\([^)]{0,120}mode:\s*:object/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-502',
    skill: 'ruby/security',
    message:
      'Unsafe deserialization (Marshal / YAML.unsafe_load / Oj object mode) of untrusted data runs gadget chains.',
    help: 'Use JSON or YAML.safe_load.',
  },
  {
    id: 'rb-sql-interpolation',
    languages: RB,
    regex:
      /\.(?:where|find_by_sql|select|order|joins|having|group|pluck|exists\?|execute|exec_query|from|lock)\s*\(\s*"[^"]{0,300}#\{/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-89',
    skill: 'ruby/security',
    message: 'SQL fragment with string interpolation: SQL injection.',
    help: 'Use placeholders: where("name = ?", name) or hash conditions.',
  },
  {
    id: 'rb-html-safe',
    languages: RB,
    paths: ['**/*.erb', '**/*.haml', '**/*.slim'],
    regex: /\.html_safe\b|\braw\s*\(|<%==/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-79',
    skill: 'ruby/rails/core',
    message: '`html_safe` / `raw` / `<%==` disable escaping: user content rendered this way is XSS.',
    help: 'Let the template escape, or sanitize() the HTML.',
  },
  {
    id: 'rb-permit-all',
    languages: RB,
    regex: /\bparams\.permit!|\bpermit_all_parameters\s*=\s*true/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-915',
    skill: 'ruby/rails/core',
    message: 'All request params permitted: mass assignment of admin/role/owner fields.',
    help: 'Permit an explicit list of attributes.',
  },
  {
    id: 'rb-csrf-skip',
    languages: RB,
    regex:
      /\bskip_before_action\s+:verify_authenticity_token|\bskip_forgery_protection\b|\bprotect_from_forgery\s+with:\s*:null_session/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-352',
    skill: 'ruby/rails/core',
    message: 'CSRF verification skipped: cookie-authenticated actions can be forged cross-site.',
    help: 'Keep CSRF protection unless the endpoint is token-authenticated only.',
  },
  {
    id: 'rb-kernel-open',
    languages: RB,
    regex: /(?<![\w.:])open\s*\(\s*(?:params\b|request\.|url\b|uri\b)|\bURI\.open\s*\(\s*params\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'ruby/security',
    message: '`Kernel#open` / `URI.open` with user input: a leading `|` runs a command, URLs enable SSRF.',
    help: 'Use File.open / Net::HTTP with validated values.',
  },
];

/** Rust rules. */
const RUST_RULES: PatternRule[] = [
  {
    id: 'rs-unwrap-input',
    languages: RS,
    regex:
      /\b(?:parse(?:::<[^>]{1,40}>)?|from_str|from_slice|from_utf8|from_reader|read_to_string|read_line|var|var_os|header|headers|query|json|body|bytes|decode|try_into|try_from|recv)\s*\([^\n]{0,120}\)\s*\.(?:unwrap|expect)\s*\(/,
    severity: 'minor',
    category: 'error-handling',
    confidence: 0.4,
    skill: 'rust/errors/swallowed',
    message: '`unwrap()` / `expect()` on parsed or external input panics on bad data (denial of service).',
    help: 'Propagate with `?` or handle the error.',
  },
  {
    id: 'rs-unsafe-memory',
    languages: RS,
    regex:
      /\b(?:mem::)?transmute(?:::<[^>]{1,80}>)?\s*\(|\bslice::from_raw_parts(?:_mut)?\s*\(|\.set_len\s*\(|\.get_unchecked(?:_mut)?\s*\(|\bMaybeUninit::uninit\(\)\.assume_init\(\)|\bmem::(?:uninitialized|zeroed)\s*(?:::<[^>]{1,80}>)?\s*\(/,
    severity: 'minor',
    category: 'bug',
    confidence: 0.4,
    skill: 'rust/unsafe-ffi/raw-pointers',
    message: 'Unsafe memory operation: a wrong length/type/initialization here is undefined behaviour.',
    help: 'Prefer safe APIs; document and assert the invariants that make this sound.',
  },
  {
    id: 'rs-shell-command',
    languages: RS,
    regex:
      /Command::new\s*\(\s*"(?:sh|bash|\/bin\/sh|\/bin\/bash|cmd(?:\.exe)?)"\s*\)[^;]{0,120}\.args?\s*\(\s*(?:&?\[\s*)?"(?:-c|\/C|\/c)"/,
    window: 2,
    severity: 'major',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-78',
    skill: 'rust/security/path-traversal',
    message: 'Command run through a shell (`sh -c`): interpolated values inject commands.',
    help: 'Run the program directly with .arg() per argument.',
  },
  {
    id: 'rs-tls-danger',
    languages: RS,
    regex:
      /\bdanger_accept_invalid_(?:certs|hostnames)\s*\(\s*true\s*\)|\.dangerous\(\)\s*\.set_certificate_verifier|\bset_verify\s*\(\s*SslVerifyMode::NONE\s*\)/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-295',
    skill: 'rust/security/tls',
    message: 'TLS certificate/hostname verification disabled: MITM possible.',
    help: 'Add private CAs as root certificates instead.',
  },
  {
    id: 'rs-sql-format',
    languages: RS,
    regex:
      /format!\s*\(\s*"\s*(?:SELECT\b[^"]{0,200}\bFROM|INSERT\s+INTO|UPDATE\s+[\w."]{1,80}\s+SET|DELETE\s+FROM)\b[^"]{0,300}\{/i,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-89',
    skill: 'rust/database/sqlx/queries',
    message: 'SQL built with format!: values are not parameterized (SQL injection).',
    help: 'Use bind parameters (sqlx::query!(…, value) / .bind()).',
  },
];

/** Rules for PHP, JVM languages, C#, Go, Ruby and Rust. */
export const BACKEND_RULES: PatternRule[] = [
  ...PHP_RULES,
  ...JVM_RULES,
  ...CSHARP_RULES,
  ...GO_RULES,
  ...RUBY_RULES,
  ...RUST_RULES,
];
