import type { PatternRule } from './types';

const PY = ['python'] as const;

/** Python rules. */
export const PYTHON_RULES: PatternRule[] = [
  {
    id: 'py-eval-exec',
    languages: PY,
    regex: /(?<![\w.])(?:eval|exec)\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-95',
    skill: 'python/security/code-execution',
    message:
      '`eval()`/`exec()` run strings as Python code: code injection if any part is attacker-influenced.',
    help: 'Use ast.literal_eval for literals, json for data, or an explicit dispatch table.',
  },
  {
    id: 'py-shell-true',
    languages: PY,
    regex: /\bshell\s*=\s*True\b/,
    // A constant command string without formatting is not injectable.
    notIf: /\(\s*[rb]?(?:"[^"{}%]*"|'[^'{}%]*')\s*,\s*(?:[\w.]+\s*=\s*[\w.'"]+\s*,\s*){0,5}shell\s*=\s*True/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'python/security/injection',
    message: 'subprocess with `shell=True`: shell metacharacters in any interpolated value inject commands.',
    help: 'Pass an argument list without shell=True.',
  },
  {
    id: 'py-os-system',
    languages: PY,
    regex: /\bos\.(?:system|popen)\s*\(\s*(?:f["']|[^)]{0,200}(?:\+|%\s*[\w(]|\.format\s*\())/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-78',
    skill: 'python/security/injection',
    message: '`os.system`/`os.popen` with a built string: command injection if any part is user-controlled.',
    help: 'Use subprocess.run([...]) with an argument list.',
  },
  {
    id: 'py-pickle-load',
    languages: PY,
    regex:
      /\b(?:pickle|cPickle|_pickle|dill|cloudpickle|shelve|jsonpickle|joblib|marshal)\.(?:loads?|open|Unpickler|decode)\s*\(/,
    severity: 'major',
    category: 'security',
    confidence: 0.5,
    cwe: 'CWE-502',
    skill: 'python/security/deserialization',
    message: 'Unpickling runs code embedded in the data: never load pickles from untrusted sources.',
    help: 'Use JSON or another data-only format; sign and verify data if pickle is unavoidable.',
  },
  {
    id: 'py-torch-load',
    languages: PY,
    regex: /\btorch\.load\s*\(/,
    notIf: /weights_only\s*=\s*True/,
    window: 2,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-502',
    skill: 'python/security/deserialization',
    message:
      '`torch.load` without `weights_only=True` unpickles arbitrary objects (code execution on untrusted files).',
    help: 'Pass weights_only=True or use safetensors.',
  },
  {
    id: 'py-yaml-load',
    languages: PY,
    regex: /\byaml\.(?:unsafe_load(?:_all)?|load(?:_all)?)\s*\(/,
    notIf: /\bLoader\s*=\s*(?:yaml\.)?C?(?:Safe|Base)Loader\b/,
    window: 1,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-502',
    skill: 'python/security/deserialization',
    message: '`yaml.load` without SafeLoader can construct arbitrary Python objects (code execution).',
    help: 'Use yaml.safe_load().',
  },
  {
    id: 'py-verify-false',
    languages: PY,
    regex: /\bverify\s*=\s*False\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-295',
    skill: 'python/security/tls-urls',
    message: 'TLS certificate verification disabled (`verify=False`): traffic can be intercepted.',
    help: 'Keep verification on; point `verify` at a CA bundle for private CAs.',
  },
  {
    id: 'py-ssl-unverified',
    languages: PY,
    regex:
      /\bssl\._create_unverified_context\s*\(|\bcert_reqs\s*=\s*(?:ssl\.)?CERT_NONE\b|\.check_hostname\s*=\s*False\b|\bverify_mode\s*=\s*(?:ssl\.)?CERT_NONE\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-295',
    skill: 'python/security/tls-urls',
    message: 'SSL context without certificate/hostname verification: MITM possible.',
    help: 'Use ssl.create_default_context().',
  },
  {
    id: 'py-flask-debug',
    languages: PY,
    regex: /\.run\s*\([^)]{0,200}\bdebug\s*=\s*True\b|\bapp\.debug\s*=\s*True\b/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-489',
    skill: 'python/flask/config-sessions',
    message: 'Flask debug mode exposes the Werkzeug debugger, which allows remote code execution.',
    help: 'Enable debug only from the environment in development.',
  },
  {
    id: 'py-django-debug',
    languages: PY,
    regex: /^\s*DEBUG\s*=\s*True\b/,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-489',
    skill: 'python/django/settings-security',
    message: '`DEBUG = True` leaks stack traces, settings and SQL to visitors if it reaches production.',
    help: 'Read DEBUG from the environment and default to False.',
  },
  {
    id: 'py-csrf-exempt',
    languages: PY,
    regex: /@csrf_exempt\b/,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-352',
    skill: 'python/django/auth-sessions',
    message: '`@csrf_exempt` removes CSRF protection: state-changing requests can be forged cross-site.',
    help: 'Keep CSRF protection for cookie-authenticated views.',
  },
  {
    id: 'py-mktemp',
    languages: PY,
    regex: /\btempfile\.mktemp\s*\(/,
    severity: 'minor',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-377',
    skill: 'python/security/paths-archives',
    message: '`tempfile.mktemp` is race-prone: another process can create the file first (symlink attacks).',
    help: 'Use tempfile.mkstemp or NamedTemporaryFile.',
  },
  {
    id: 'py-except-pass',
    languages: PY,
    regex: /^\s*except\b[^:\n]{0,120}:\s*(?:pass|\.\.\.)\s*(?:#[^\n]*)?$/m,
    window: 1,
    severity: 'minor',
    category: 'error-handling',
    confidence: 0.4,
    skill: 'python/core/exceptions',
    message:
      'Exception swallowed with `pass`: failures are silently ignored and state may be left inconsistent.',
    help: 'Handle or log the exception, and catch the narrowest type.',
  },
  {
    id: 'py-mutable-default',
    languages: PY,
    regex: /\bdef\s+\w+\s*\([^)]{0,300}=\s*(?:\[\]|\{\}|set\(\)|list\(\)|dict\(\))\s*[,)]/,
    severity: 'minor',
    category: 'bug',
    confidence: 0.5,
    skill: 'python/core/shared-mutables',
    message:
      'Mutable default argument is created once and shared between calls: state leaks across invocations.',
    help: 'Default to None and create the list/dict inside the function.',
  },
  {
    id: 'py-is-literal',
    languages: PY,
    regex:
      /\bis\s+(?:not\s+)?(?:-?\d+(?:\.\d+)?|[bru]?["'][^"'\n]{0,80}["'])(?=\s*(?:$|[):,#\]]|and\b|or\b|if\b|else\b))/,
    severity: 'major',
    category: 'bug',
    confidence: 0.6,
    skill: 'python/core/equality-hashing',
    message:
      '`is` compares identity, not value: comparing with an int/str literal depends on interning and breaks.',
    help: 'Use == / !=.',
  },
  {
    id: 'py-jwt-no-verify',
    languages: PY,
    regex: /\bjwt\.decode\s*\([^)]{0,200}(?:verify\s*=\s*False|["']verify_signature["']\s*:\s*False)/,
    window: 2,
    severity: 'major',
    category: 'security',
    confidence: 0.6,
    cwe: 'CWE-347',
    skill: 'security/auth',
    message: 'JWT decoded without signature verification: forged tokens are accepted.',
    help: 'Verify the signature with an explicit algorithms list.',
  },
  {
    id: 'py-requests-no-timeout',
    languages: PY,
    regex: /\b(?:requests|httpx)\.(?:get|post|put|patch|delete|head|options|request)\s*\(/,
    notIf: /\btimeout\s*=/,
    window: 3,
    severity: 'minor',
    category: 'performance',
    confidence: 0.3,
    skill: 'python/core/http-clients',
    message: 'HTTP request without a timeout can hang the worker forever when the peer stalls.',
    help: 'Pass timeout=(connect, read).',
  },
  {
    id: 'py-sql-fstring-execute',
    languages: PY,
    regex: /\.(?:raw|extra|execute|executemany|executescript|exec_driver_sql)\s*\(\s*f["']/,
    severity: 'major',
    category: 'security',
    confidence: 0.55,
    cwe: 'CWE-89',
    skill: 'python/security/injection',
    message: 'SQL passed as an f-string: interpolated values are not parameterized (SQL injection).',
    help: 'Use placeholders (%s / :name) and pass the values separately.',
  },
  {
    id: 'py-autoescape-off',
    languages: ['python', 'html'],
    regex:
      /\bmark_safe\s*\(|\bMarkup\s*\(\s*f["']|\|\s*safe\b|\bautoescape\s*=\s*False\b|\{%\s*autoescape\s+off\s*%\}/,
    severity: 'minor',
    category: 'security',
    confidence: 0.4,
    cwe: 'CWE-79',
    skill: 'python/security/templates',
    message: 'Template auto-escaping bypassed: user-controlled content rendered this way is XSS.',
    help: 'Keep auto-escaping on; sanitize HTML that must be rendered raw.',
  },
  {
    id: 'py-tar-extractall',
    languages: PY,
    regex: /\.extractall\s*\(/,
    notIf: /filter\s*=\s*["'](?:data|tar)["']/,
    window: 1,
    severity: 'minor',
    category: 'security',
    confidence: 0.45,
    cwe: 'CWE-22',
    skill: 'python/security/paths-archives',
    message: '`extractall` without a filter allows path traversal ("zip slip") from crafted archives.',
    help: "Pass filter='data' (Python 3.12+) or validate member paths.",
  },
];
